learning_templates/basicApp/urls.py
from django.conf.urls import url
from basicApp import views
#template tagging
app_name= 'basicApp'
urlpatterns = [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'other/$',views.other,name='other')
]

learning_templates/learning_templates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basicApp import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basicApp/',include('basicApp.urls'))
]

learning_templates/basicApp/models.py
from django.db import models

# Create your models here.

learning_templates/basicApp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict={'text':'hello world','number':100}
    return render(request, 'basicApp/index.html',context=context_dict)

def other(request):
    return render(request, 'basicApp/other.html')

def relative(request):
    return render(request, 'basicApp/relative_url_templates.html')

learning_templates/templates/basicApp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar sticky-top navbar-light bg-light">
      <div class="container">
        <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'index'%}">Fixed top</a></li>
        <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
        <li> <a class="navbar-link" href="{% url 'basicApp:other' %}">Other</a> </li>
        </ul>
      </div>
      </nav>
      <div class="container">
        {% block body_block %}
        <!-- Cualquier cosa fuera de esto sera hererado si tu lo extiendes -->
        {% endblock %}
      </div>
  </body>
</html>

learning_templates/templates/basicApp/index.html
<!DOCTYPE html>

{% extends "basicApp/base.html" %}
{% load  corte  %}
  {% block body_block %}
    <h1>WELCOME   TO INDEX</h1>
    <h2>This is index.html page showing</h2>
    {{ text|upper }}
    {{ number|add:"99" }}
    {{ text|cut:'hello'}}
  {% endblock %}

learning_templates/templates/basicApp/other.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>This is  an example of tempalte inheritance</h2>
  {% endblock %}

learning_templates/templates/basicApp/realtive_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basicApp:other' %}">other</a><!--Se coloca el app_name del urls py y el name del mapeo y esta es la que usa django 2-->
    <!-- <a href="basicApp/other.html">THe OTHER PAGE</a> -->
    <a href="{% url 'admin:index' %}">admin</a>
    <a href="{% url 'index' %}">index</a>
  </body>
</html>